#include "SpellAttribute.h"

QString attributesDescription[7][32][2] = {
    {
        { "UNK0", "0" },
        { "RANGED", "1 All ranged abilites have this flag" },
        { "ON_NEXT_SWING_1", "2 on next swing" },
        { "UNK3", "3 not set in 3.0.3" },
        { "UNK4", "4 isAbility" },
        { "TRADESPELL", "5 trade spells, will be added by client to a sublist of profession spell" },
        { "PASSIVE", "6 Passive spell" },
        { "UNK7", "7 can't be linked in chat?" },
        { "UNK8", "8 hide created item in tooltip (for effect=24)" },
        { "UNK9", "9" },
        { "ON_NEXT_SWING_2", "10 on next swing 2" },
        { "UNK11", "11" },
        { "DAYTIME_ONLY", "12 only useable at daytime, not set in 2.4.2" },
        { "NIGHT_ONLY", "13 only useable at night, not set in 2.4.2" },
        { "INDOORS_ONLY", "14 only useable indoors, not set in 2.4.2" },
        { "OUTDOORS_ONLY", "15 Only useable outdoors." },
        { "NOT_SHAPESHIFT", "16 Not while shapeshifted" },
        { "ONLY_STEALTHED", "17 Must be in stealth" },
        { "UNK18", "18" },
        { "LEVEL_DAMAGE_CALCULATION", "19 spelldamage depends on caster level" },
        { "STOP_ATTACK_TARGET", "20 Stop attack after use this spell (and not begin attack if use)" },
        { "IMPOSSIBLE_DODGE_PARRY_BLOCK", "21 Cannot be dodged/parried/blocked" },
        { "SET_TRACKING_TARGET", "22 SetTrackingTarget" },
        { "UNK23", "23 castable while dead?" },
        { "CASTABLE_WHILE_MOUNTED", "24 castable while mounted" },
        { "DISABLED_WHILE_ACTIVE", "25 Activate and start cooldown after aura fade or remove summoned creature or go" },
        { "UNK26", "26" },
        { "CASTABLE_WHILE_SITTING", "27 castable while sitting" },
        { "CANT_USED_IN_COMBAT", "28 Cannot be used in combat" },
        { "UNAFFECTED_BY_INVULNERABILITY", "29 unaffected by invulnerability (hmm possible not...)" },
        { "UNK30", "30 breakable by damage?" },
        { "CANT_CANCEL", "31 positive aura can't be canceled" },
    },
    {
        { "EX_UNK0", "0" },
        { "EX_DRAIN_ALL_POWER", "1 use all power (Only paladin Lay of Hands and Bunyanize)" },
        { "EX_CHANNELED_1", "2 channeled 1" },
        { "EX_UNK3", "3" },
        { "EX_UNK4", "4" },
        { "EX_NOT_BREAK_STEALTH", "5 Not break stealth" },
        { "EX_CHANNELED_2", "6 channeled 2" },
        { "EX_NEGATIVE", "7" },
        { "EX_NOT_IN_COMBAT_TARGET", "8 Spell req target not to be in combat state" },
        { "EX_UNK9", "9" },
        { "EX_NO_THREAT", "10 no generates threat on cast 100%" },
        { "EX_UNK11", "11" },
        { "EX_UNK12", "12" },
        { "EX_FARSIGHT", "13 related to farsight" },
        { "EX_UNK14", "14" },
        { "EX_DISPEL_AURAS_ON_IMMUNITY", "15 remove auras on immunity" },
        { "EX_UNAFFECTED_BY_SCHOOL_IMMUNE", "16 unaffected by school immunity" },
        { "EX_UNK17", "17 for auras SPELL_AURA_TRACK_CREATURES, SPELL_AURA_TRACK_RESOURCES and SPELL_AURA_TRACK_STEALTHED select non-stacking tracking spells" },
        { "EX_UNK18", "18" },
        { "EX_UNK19", "19" },
        { "EX_REQ_TARGET_COMBO_POINTS", "20 Req combo points on target" },
        { "EX_UNK21", "21" },
        { "EX_REQ_COMBO_POINTS", "22 Use combo points (in 4.x not required combo point target selected)" },
        { "EX_UNK23", "23" },
        { "EX_UNK24", "24 Req fishing pole??" },
        { "EX_UNK25", "25 not set in 2.4.2" },
        { "EX_UNK26", "26" },
        { "EX_UNK27", "27" },
        { "EX_UNK28", "28" },
        { "EX_UNK29", "29" },
        { "EX_UNK30", "30 overpower" },
        { "EX_UNK31", "31" },
    },
    {
        { "EX2_UNK0", "0" },
        { "EX2_UNK1", "1" },
        { "EX2_CANT_REFLECTED", "2 ? used for detect can or not spell reflected // do not need LOS (e.g. 18220 since 3.3.3)" },
        { "EX2_UNK3", "3 auto targeting? (e.g. fishing skill enhancement items since 3.3.3)" },
        { "EX2_UNK4", "4" },
        { "EX2_AUTOREPEAT_FLAG", "5" },
        { "EX2_UNK6", "6 only usable on tabbed by yourself" },
        { "EX2_UNK7", "7" },
        { "EX2_UNK8", "8 not set in 2.4.2" },
        { "EX2_UNK9", "9" },
        { "EX2_UNK10", "10" },
        { "EX2_HEALTH_FUNNEL", "11" },
        { "EX2_UNK12", "12" },
        { "EX2_UNK13", "13" },
        { "EX2_UNK14", "14" },
        { "EX2_UNK15", "15 not set in 2.4.2" },
        { "EX2_UNK16", "16" },
        { "EX2_UNK17", "17 suspend weapon timer instead of resetting it, (?Hunters Shot and Stings only have this flag?)" },
        { "EX2_UNK18", "18 Only Revive pet - possible req dead pet" },
        { "EX2_NOT_NEED_SHAPESHIFT", "19 does not necessary need shapeshift (pre-3.x not have passive spells with this attribute)" },
        { "EX2_UNK20", "20" },
        { "EX2_DAMAGE_REDUCED_SHIELD", "21 for ice blocks, pala immunity buffs, priest absorb shields, but used also for other spells -> not sure!" },
        { "EX2_UNK22", "22" },
        { "EX2_UNK23", "23 Only mage Arcane Concentration have this flag" },
        { "EX2_UNK24", "24" },
        { "EX2_UNK25", "25" },
        { "EX2_UNK26", "26 unaffected by school immunity" },
        { "EX2_UNK27", "27" },
        { "EX2_UNK28", "28 no breaks stealth if it fails??" },
        { "EX2_CANT_CRIT", "29 Spell can't crit" },
        { "EX2_UNK30", "30" },
        { "EX2_FOOD_BUFF", "31 Food or Drink Buff (like Well Fed)" },
    },
    {
        { "EX3_UNK0", "0" },
        { "EX3_UNK1", "1" },
        { "EX3_UNK2", "2" },
        { "EX3_UNK3", "3" },
        { "EX3_UNK4", "4 Druid Rebirth only this spell have this flag" },
        { "EX3_UNK5", "5" },
        { "EX3_UNK6", "6" },
        { "EX3_UNK7", "7 create a separate (de)buff stack for each caster" },
        { "EX3_TARGET_ONLY_PLAYER", "8 Can target only player" },
        { "EX3_UNK9", "9" },
        { "EX3_MAIN_HAND", "10 Main hand weapon required" },
        { "EX3_BATTLEGROUND", "11 Can casted only on battleground" },
        { "EX3_CAST_ON_DEAD", "12 target is a dead player (not every spell has this flag)" },
        { "EX3_UNK13", "13" },
        { "EX3_UNK14", "14 \"Honorless Target\" only this spells have this flag" },
        { "EX3_UNK15", "15 Auto Shoot, Shoot, Throw,  - this is autoshot flag" },
        { "EX3_UNK16", "16 no triggers effects that trigger on casting a spell??" },
        { "EX3_NO_INITIAL_AGGRO", "17 Causes no aggro if not missed" },
        { "EX3_CANT_MISS", "18 Spell should always hit its target" },
        { "EX3_UNK19", "19" },
        { "EX3_DEATH_PERSISTENT", "20 Death persistent spells" },
        { "EX3_UNK21", "21" },
        { "EX3_REQ_WAND", "22 Req wand" },
        { "EX3_UNK23", "23" },
        { "EX3_REQ_OFFHAND", "24 Req offhand weapon" },
        { "EX3_UNK25", "25 no cause spell pushback ?" },
        { "EX3_UNK26", "26" },
        { "EX3_UNK27", "27" },
        { "EX3_UNK28", "28" },
        { "EX3_UNK29", "29" },
        { "EX3_UNK30", "30" },
        { "EX3_UNK31", "31" },
    },
    {
        { "EX4_UNK0", "0" },
        { "EX4_UNK1", "1 proc on finishing move?" },
        { "EX4_UNK2", "2" },
        { "EX4_UNK3", "3" },
        { "EX4_UNK4", "4 This will no longer cause guards to attack on use??" },
        { "EX4_UNK5", "5" },
        { "EX4_NOT_STEALABLE", "6 although such auras might be dispellable, they cannot be stolen" },
        { "EX4_UNK7", "7" },
        { "EX4_STACK_DOT_MODIFIER", "8 no effect on non DoTs?" },
        { "EX4_UNK9", "9" },
        { "EX4_SPELL_VS_EXTEND_COST", "10 Rogue Shiv have this flag" },
        { "EX4_UNK11", "11" },
        { "EX4_UNK12", "12" },
        { "EX4_UNK13", "13" },
        { "EX4_UNK14", "14" },
        { "EX4_UNK15", "15" },
        { "EX4_NOT_USABLE_IN_ARENA", "16 not usable in arena" },
        { "EX4_USABLE_IN_ARENA", "17 usable in arena" },
        { "EX4_UNK18", "18" },
        { "EX4_UNK19", "19" },
        { "EX4_UNK20", "20 do not give \"more powerful spell\" error message" },
        { "EX4_UNK21", "21" },
        { "EX4_UNK22", "22" },
        { "EX4_UNK23", "23" },
        { "EX4_UNK24", "24" },
        { "EX4_UNK25", "25 pet scaling auras" },
        { "EX4_CAST_ONLY_IN_OUTLAND", "26 Can only be used in Outland." },
        { "EX4_UNK27", "27" },
        { "EX4_UNK28", "28" },
        { "EX4_UNK29", "29" },
        { "EX4_UNK30", "30" },
        { "EX4_UNK31", "31" },
    },
    {
        { "EX5_UNK0", "0" },
        { "EX5_NO_REAGENT_WHILE_PREP", "1 not need reagents if UNIT_FLAG_PREPARATION" },
        { "EX5_UNK2", "2 removed at enter arena (e.g. 31850 since 3.3.3)" },
        { "EX5_USABLE_WHILE_STUNNED", "3 usable while stunned" },
        { "EX5_UNK4", "4" },
        { "EX5_SINGLE_TARGET_SPELL", "5 Only one target can be apply at a time" },
        { "EX5_UNK6", "6" },
        { "EX5_UNK7", "7" },
        { "EX5_UNK8", "8" },
        { "EX5_START_PERIODIC_AT_APPLY", "9  begin periodic tick at aura apply" },
        { "EX5_UNK10", "10" },
        { "EX5_UNK11", "11" },
        { "EX5_UNK12", "12" },
        { "EX5_UNK13", "13 haste affects duration (e.g. 8050 since 3.3.3)" },
        { "EX5_UNK14", "14" },
        { "EX5_UNK15", "15" },
        { "EX5_UNK16", "16" },
        { "EX5_USABLE_WHILE_FEARED", "17 usable while feared" },
        { "EX5_USABLE_WHILE_CONFUSED", "18 usable while confused" },
        { "EX5_UNK19", "19" },
        { "EX5_UNK20", "20" },
        { "EX5_UNK21", "21" },
        { "EX5_UNK22", "22" },
        { "EX5_UNK23", "23" },
        { "EX5_UNK24", "24" },
        { "EX5_UNK25", "25" },
        { "EX5_UNK26", "26" },
        { "EX5_UNK27", "27" },
        { "EX5_UNK28", "28" },
        { "EX5_UNK29", "29" },
        { "EX5_UNK30", "30" },
        { "EX5_UNK31", "31 Forces all nearby enemies to focus attacks caster" }
    },
    {
        { "EX6_UNK0", "0 Only Move spell have this flag" },
        { "EX6_ONLY_IN_ARENA", "1 only usable in arena, not used in 3.2.0a and early" },
        { "EX6_UNK2", "2" },
        { "EX6_UNK3", "3" },
        { "EX6_UNK4", "4" },
        { "EX6_UNK5", "5" },
        { "EX6_UNK6", "6" },
        { "EX6_UNK7", "7" },
        { "EX6_UNK8", "8" },
        { "EX6_UNK9", "9" },
        { "EX6_UNK10", "10" },
        { "EX6_NOT_IN_RAID_INSTANCE", "11 not usable in raid instance" },
        { "EX6_UNK12", "12 for auras SPELL_AURA_TRACK_CREATURES, SPELL_AURA_TRACK_RESOURCES and SPELL_AURA_TRACK_STEALTHED select non-stacking tracking spells" },
        { "EX6_UNK13", "13" },
        { "EX6_UNK14", "14" },
        { "EX6_UNK15", "15 not set in 3.0.3" },
        { "EX6_UNK16", "16" },
        { "EX6_UNK17", "17" },
        { "EX6_UNK18", "18" },
        { "EX6_UNK19", "19" },
        { "EX6_UNK20", "20" },
        { "EX6_UNK21", "21" },
        { "EX6_UNK22", "22" },
        { "EX6_UNK23", "23 not set in 3.0.3" },
        { "EX6_UNK24", "24 not set in 3.0.3" },
        { "EX6_UNK25", "25 not set in 3.0.3" },
        { "EX6_UNK26", "26 not set in 3.0.3" },
        { "EX6_UNK27", "27 not set in 3.0.3" },
        { "EX6_UNK28", "28 not set in 3.0.3" },
        { "EX6_UNK29", "29 do not apply damage mods (usually in cases where it has already been applied)" },
        { "EX6_UNK30", "30 not set in 3.0.3" },
        { "EX6_UNK31", "31 not set in 3.0.3" }
    }
};

SpellAttribute::SpellAttribute(QString &name, QString &description)
{
    _name = name;
    _description = description;
}

const QString         &SpellAttribute::getName() const
{
    return _name;
}

const QString         &SpellAttribute::getDescription() const
{
    return _description;
}

QList<SpellAttribute>    SpellAttribute::create(SpellEntry *spell)
{
    QList<SpellAttribute>   list;
    unsigned int            attributes[] =
    {
        spell->Attributes,
        spell->AttributesEx,
        spell->AttributesEx2,
        spell->AttributesEx3,
        spell->AttributesEx4,
        spell->AttributesEx5,
        spell->AttributesEx6
    };

    for (int e = 0 ; e < 7 ; e++)
    {
        for (unsigned int i = 0, j = 1; i < 32 ; i++, j <<= 1)
        {
            if ((attributes[e] & j) == j)
            {
                list.append(SpellAttribute(attributesDescription[e][i][0], attributesDescription[e][i][1]));
            }
        }
    }
    return list;
}
